# site settings
title: Projet ISN
subtitle: Reconnaissance d'Image par Réseau de Neurone 
email: zakari-94@live.fr
description: Projet D'initiation au Science de l'Ingénieur: <br />initiation a la reconnaissance d'image et à l'intelligence artificielle
baseurl: "/ProjetISN_ReconnaissanceImage" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url:https://github.com/zakbena/

# build settings
markdown: kramdown

sass:
  style: compressed
